/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFundKeeper, IFundKeeperInterface } from "../IFundKeeper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawToController",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFundKeeper__factory {
  static readonly abi = _abi;
  static createInterface(): IFundKeeperInterface {
    return new utils.Interface(_abi) as IFundKeeperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFundKeeper {
    return new Contract(address, _abi, signerOrProvider) as IFundKeeper;
  }
}
