/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPriceCalculatorInterface extends ethers.utils.Interface {
  functions: {
    "getLargestPool(address,address[])": FunctionFragment;
    "getPrice(address,address)": FunctionFragment;
    "getPriceFromLp(address,address)": FunctionFragment;
    "getPriceWithDefaultOutput(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLargestPool",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceFromLp",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceWithDefaultOutput",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLargestPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceFromLp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceWithDefaultOutput",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPriceCalculator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPriceCalculatorInterface;

  functions: {
    getLargestPool(
      token: string,
      usedLps: string[],
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;

    getPrice(
      token: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPriceFromLp(
      lpAddress: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPriceWithDefaultOutput(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getLargestPool(
    token: string,
    usedLps: string[],
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, string]>;

  getPrice(
    token: string,
    outputToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceFromLp(
    lpAddress: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceWithDefaultOutput(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getLargestPool(
      token: string,
      usedLps: string[],
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;

    getPrice(
      token: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceFromLp(
      lpAddress: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceWithDefaultOutput(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getLargestPool(
      token: string,
      usedLps: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      token: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceFromLp(
      lpAddress: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceWithDefaultOutput(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLargestPool(
      token: string,
      usedLps: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      token: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceFromLp(
      lpAddress: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceWithDefaultOutput(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
