/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface NotifyHelperInterface extends ethers.utils.Interface {
  functions: {
    "VERSION()": FunctionFragment;
    "alreadyNotified(address)": FunctionFragment;
    "alreadyNotifiedList(uint256)": FunctionFragment;
    "alreadyNotifiedListLength()": FunctionFragment;
    "clearNotifiedStatuses()": FunctionFragment;
    "controller()": FunctionFragment;
    "created()": FunctionFragment;
    "initializeControllable(address)": FunctionFragment;
    "isController(address)": FunctionFragment;
    "isGovernance(address)": FunctionFragment;
    "moveTokensToController(address,uint256)": FunctionFragment;
    "notifyVaults(uint256[],address[],uint256,address)": FunctionFragment;
    "psVault()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "alreadyNotified",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "alreadyNotifiedList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "alreadyNotifiedListLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clearNotifiedStatuses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "created", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initializeControllable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isGovernance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "moveTokensToController",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyVaults",
    values: [BigNumberish[], string[], BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "psVault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "alreadyNotified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alreadyNotifiedList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alreadyNotifiedListLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearNotifiedStatuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "created", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeControllable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moveTokensToController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "psVault", data: BytesLike): Result;

  events: {
    "TokenMoved(address,uint256)": EventFragment;
    "UpdateController(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokenMoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateController"): EventFragment;
}

export class NotifyHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: NotifyHelperInterface;

  functions: {
    VERSION(overrides?: CallOverrides): Promise<[string]>;

    alreadyNotified(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    alreadyNotifiedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    alreadyNotifiedListLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    clearNotifiedStatuses(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controller(overrides?: CallOverrides): Promise<[string] & { adr: string }>;

    created(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { ts: BigNumber }>;

    initializeControllable(
      _controller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isController(_adr: string, overrides?: CallOverrides): Promise<[boolean]>;

    isGovernance(_adr: string, overrides?: CallOverrides): Promise<[boolean]>;

    moveTokensToController(
      _token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    notifyVaults(
      amounts: BigNumberish[],
      vaults: string[],
      sum: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    psVault(overrides?: CallOverrides): Promise<[string]>;
  };

  VERSION(overrides?: CallOverrides): Promise<string>;

  alreadyNotified(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  alreadyNotifiedList(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  alreadyNotifiedListLength(overrides?: CallOverrides): Promise<BigNumber>;

  clearNotifiedStatuses(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controller(overrides?: CallOverrides): Promise<string>;

  created(overrides?: CallOverrides): Promise<BigNumber>;

  initializeControllable(
    _controller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isController(_adr: string, overrides?: CallOverrides): Promise<boolean>;

  isGovernance(_adr: string, overrides?: CallOverrides): Promise<boolean>;

  moveTokensToController(
    _token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  notifyVaults(
    amounts: BigNumberish[],
    vaults: string[],
    sum: BigNumberish,
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  psVault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    VERSION(overrides?: CallOverrides): Promise<string>;

    alreadyNotified(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    alreadyNotifiedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    alreadyNotifiedListLength(overrides?: CallOverrides): Promise<BigNumber>;

    clearNotifiedStatuses(overrides?: CallOverrides): Promise<void>;

    controller(overrides?: CallOverrides): Promise<string>;

    created(overrides?: CallOverrides): Promise<BigNumber>;

    initializeControllable(
      _controller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isController(_adr: string, overrides?: CallOverrides): Promise<boolean>;

    isGovernance(_adr: string, overrides?: CallOverrides): Promise<boolean>;

    moveTokensToController(
      _token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    notifyVaults(
      amounts: BigNumberish[],
      vaults: string[],
      sum: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    psVault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    TokenMoved(
      token?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { token: string; amount: BigNumber }
    >;

    UpdateController(
      oldValue?: null,
      newValue?: null
    ): TypedEventFilter<
      [string, string],
      { oldValue: string; newValue: string }
    >;
  };

  estimateGas: {
    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    alreadyNotified(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    alreadyNotifiedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    alreadyNotifiedListLength(overrides?: CallOverrides): Promise<BigNumber>;

    clearNotifiedStatuses(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<BigNumber>;

    created(overrides?: CallOverrides): Promise<BigNumber>;

    initializeControllable(
      _controller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isController(_adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isGovernance(_adr: string, overrides?: CallOverrides): Promise<BigNumber>;

    moveTokensToController(
      _token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    notifyVaults(
      amounts: BigNumberish[],
      vaults: string[],
      sum: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    psVault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    alreadyNotified(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    alreadyNotifiedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    alreadyNotifiedListLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    clearNotifiedStatuses(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    created(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initializeControllable(
      _controller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isController(
      _adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isGovernance(
      _adr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    moveTokensToController(
      _token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    notifyVaults(
      amounts: BigNumberish[],
      vaults: string[],
      sum: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    psVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
